spring:
  application:
    name: BuildToCloudRun
  security:
    oauth2.resourceserver.jwt:
      jwk-set-uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"

management:
  endpoints:
    web:
      base-path: /

server:
  servlet:
    context-path: /

spring-doc:
  show-actuator: true

logging.level:
  org.springframework: DEBUG